"""phase2_borrow_orders

Revision ID: 5e2e55fa3483
Revises: e83e3643a27f
Create Date: 2026-03-19 13:10:50.555081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e2e55fa3483'
down_revision: Union[str, None] = 'e83e3643a27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'READY_FOR_PICKUP', 'DELIVERED', 'PARTIALLY_RETURNED', 'COMPLETED', 'CANCELLED', name='borrow_order_status', create_constraint=True), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('expected_return_date', sa.String(length=32), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_orders_order_no'), 'borrow_orders', ['order_no'], unique=True)
    op.create_table('borrow_approval_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('item_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='approval_task_status', create_constraint=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['borrow_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_approval_tasks_approver_id'), 'borrow_approval_tasks', ['approver_id'], unique=False)
    op.create_index(op.f('ix_borrow_approval_tasks_order_id'), 'borrow_approval_tasks', ['order_id'], unique=False)
    op.create_table('borrow_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_code_snapshot', sa.String(length=32), nullable=False),
    sa.Column('asset_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('admin_id_snapshot', sa.UUID(), nullable=False),
    sa.Column('admin_name_snapshot', sa.String(length=64), nullable=False),
    sa.Column('location_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['borrow_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_order_items_order_id'), 'borrow_order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_order_items_order_id'), table_name='borrow_order_items')
    op.drop_table('borrow_order_items')
    op.drop_index(op.f('ix_borrow_approval_tasks_order_id'), table_name='borrow_approval_tasks')
    op.drop_index(op.f('ix_borrow_approval_tasks_approver_id'), table_name='borrow_approval_tasks')
    op.drop_table('borrow_approval_tasks')
    op.drop_index(op.f('ix_borrow_orders_order_no'), table_name='borrow_orders')
    op.drop_table('borrow_orders')
    # ### end Alembic commands ###
