"""phase3_return_orders

Revision ID: 89c4ea59fa5c
Revises: 5e2e55fa3483
Create Date: 2026-03-19 13:28:15.586717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c4ea59fa5c'
down_revision: Union[str, None] = '5e2e55fa3483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('borrow_order_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'COMPLETED', name='return_order_status', create_constraint=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['borrow_order_id'], ['borrow_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_orders_borrow_order_id'), 'return_orders', ['borrow_order_id'], unique=False)
    op.create_index(op.f('ix_return_orders_order_no'), 'return_orders', ['order_no'], unique=True)
    op.create_table('return_approval_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_order_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('item_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='approval_task_status', create_type=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_approval_tasks_approver_id'), 'return_approval_tasks', ['approver_id'], unique=False)
    op.create_index(op.f('ix_return_approval_tasks_return_order_id'), 'return_approval_tasks', ['return_order_id'], unique=False)
    op.create_table('return_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_order_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('borrow_order_item_id', sa.UUID(), nullable=False),
    sa.Column('asset_code_snapshot', sa.String(length=32), nullable=False),
    sa.Column('asset_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('admin_id_snapshot', sa.UUID(), nullable=False),
    sa.Column('admin_name_snapshot', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.Enum('GOOD', 'PARTIAL_LOSS', 'FULL_LOSS', 'DAMAGED', name='return_item_condition', create_constraint=True), nullable=False),
    sa.Column('damage_type', sa.Enum('SHELL_BROKEN', 'FUNCTION_ERROR', 'ACCESSORY_DAMAGED', 'BOOT_BUT_NOT_WORKING', 'OTHER', name='damage_type_enum', create_constraint=True), nullable=True),
    sa.Column('damage_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['borrow_order_item_id'], ['borrow_order_items.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_order_items_return_order_id'), 'return_order_items', ['return_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_order_items_return_order_id'), table_name='return_order_items')
    op.drop_table('return_order_items')
    op.drop_index(op.f('ix_return_approval_tasks_return_order_id'), table_name='return_approval_tasks')
    op.drop_index(op.f('ix_return_approval_tasks_approver_id'), table_name='return_approval_tasks')
    op.drop_table('return_approval_tasks')
    op.drop_index(op.f('ix_return_orders_order_no'), table_name='return_orders')
    op.drop_index(op.f('ix_return_orders_borrow_order_id'), table_name='return_orders')
    op.drop_table('return_orders')
    # ### end Alembic commands ###
